#if !canImport(ObjectiveC)
import XCTest

extension AlertTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AlertTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

extension CertificateStatusTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CertificateStatusTests = [
        ("testDecode", testDecode),
    ]
}

extension CertificateTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CertificateTests = [
        ("testDecode", testDecode),
    ]
}

extension ChangeCipherSpecTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChangeCipherSpecTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

extension ClientHelloTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClientHelloTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

extension ClientKeyExchangeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClientKeyExchangeTests = [
        ("testDecode", testDecode),
        ("testDecodeHandshake", testDecodeHandshake),
        ("testEncode", testEncode),
        ("testEncodeHandshake", testEncodeHandshake),
    ]
}

extension ExtensionECPointFormatsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionECPointFormatsTests = [
        ("testDecode", testDecode),
        ("testDecodeExtension", testDecodeExtension),
        ("testEncode", testEncode),
        ("testEncodeExtension", testEncodeExtension),
    ]
}

extension ExtensionHeartbeatTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionHeartbeatTests = [
        ("testDecode", testDecode),
        ("testDecodeExtension", testDecodeExtension),
        ("testEncode", testEncode),
        ("testEncodeExtension", testEncodeExtension),
    ]
}

extension ExtensionRenegotiationInfoTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionRenegotiationInfoTests = [
        ("testDecode", testDecode),
        ("testDecodeExtension", testDecodeExtension),
        ("testEncode", testEncode),
        ("testEncodeExtension", testEncodeExtension),
    ]
}

extension ExtensionServerNameTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionServerNameTests = [
        ("testDecode", testDecode),
        ("testDecodeExtension", testDecodeExtension),
        ("testDecodeName", testDecodeName),
        ("testEncode", testEncode),
        ("testEncodeExtension", testEncodeExtension),
        ("testEncodeName", testEncodeName),
    ]
}

extension ExtensionSessionTicketTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionSessionTicketTests = [
        ("testDecodeEmpty", testDecodeEmpty),
        ("testDecodeEmptyRandom", testDecodeEmptyRandom),
        ("testEncodeEmpty", testEncodeEmpty),
        ("testEncodeEmptyRandom", testEncodeEmptyRandom),
    ]
}

extension ExtensionSignatureAlgorithmsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionSignatureAlgorithmsTests = [
        ("testDecode", testDecode),
        ("testDecodeExtension", testDecodeExtension),
        ("testEncode", testEncode),
        ("testEncodeExtension", testEncodeExtension),
    ]
}

extension ExtensionStatusRequestTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionStatusRequestTests = [
        ("testDecode", testDecode),
        ("testDecodeExtension", testDecodeExtension),
        ("testEncode", testEncode),
        ("testEncodeExtension", testEncodeExtension),
    ]
}

extension ExtensionSupportedGroupsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionSupportedGroupsTests = [
        ("testDecode", testDecode),
        ("testDecodeExtension", testDecodeExtension),
        ("testEncode", testEncode),
        ("testEncodeExtension", testEncodeExtension),
    ]
}

extension HandshakeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HandshakeTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

extension NewSessionTicketTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NewSessionTicketTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

extension RandomTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RandomTests = [
        ("testRandom", testRandom),
        ("testRandomBytes", testRandomBytes),
    ]
}

extension RecordLayerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RecordLayerTests = [
        ("testDecode", testDecode),
        ("testDecodeHeartbeat", testDecodeHeartbeat),
        ("testEncode", testEncode),
        ("testEncodeHeartbeat", testEncodeHeartbeat),
    ]
}

extension ServerHelloDone {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ServerHelloDone = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

extension ServerHelloTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ServerHelloTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

extension ServerKeyExchangeTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ServerKeyExchangeTests = [
        ("testDecode", testDecode),
        ("testDecodeHandshake", testDecodeHandshake),
        ("testEncode", testEncode),
        ("testEncodeHandshake", testEncodeHandshake),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AlertTests.__allTests__AlertTests),
        testCase(CertificateStatusTests.__allTests__CertificateStatusTests),
        testCase(CertificateTests.__allTests__CertificateTests),
        testCase(ChangeCipherSpecTests.__allTests__ChangeCipherSpecTests),
        testCase(ClientHelloTests.__allTests__ClientHelloTests),
        testCase(ClientKeyExchangeTests.__allTests__ClientKeyExchangeTests),
        testCase(ExtensionECPointFormatsTests.__allTests__ExtensionECPointFormatsTests),
        testCase(ExtensionHeartbeatTests.__allTests__ExtensionHeartbeatTests),
        testCase(ExtensionRenegotiationInfoTests.__allTests__ExtensionRenegotiationInfoTests),
        testCase(ExtensionServerNameTests.__allTests__ExtensionServerNameTests),
        testCase(ExtensionSessionTicketTests.__allTests__ExtensionSessionTicketTests),
        testCase(ExtensionSignatureAlgorithmsTests.__allTests__ExtensionSignatureAlgorithmsTests),
        testCase(ExtensionStatusRequestTests.__allTests__ExtensionStatusRequestTests),
        testCase(ExtensionSupportedGroupsTests.__allTests__ExtensionSupportedGroupsTests),
        testCase(HandshakeTests.__allTests__HandshakeTests),
        testCase(NewSessionTicketTests.__allTests__NewSessionTicketTests),
        testCase(RandomTests.__allTests__RandomTests),
        testCase(RecordLayerTests.__allTests__RecordLayerTests),
        testCase(ServerHelloDone.__allTests__ServerHelloDone),
        testCase(ServerHelloTests.__allTests__ServerHelloTests),
        testCase(ServerKeyExchangeTests.__allTests__ServerKeyExchangeTests),
    ]
}
#endif
